In [ ]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('ggplot')

# A bout the data :
We make scraping the data from the Aribnb web site from suadi the data have sevene columns :
- url: the url of the items that have all the data 
- name: the name of department
- header: the loaction of the place
- beds: the numbers of the beds in the departments
- bedrooms : the numbers of the rooms in departments
- date_range: how many day you will be stay in the departments
- price:  the price of staying in  the department
- rating: the rating of the people a bout the place

**import libraries**

**Read csv file**

In [ ]:
data = pd.read_csv("/kaggle/input/suida-arabia/suadi_homes (3).csv")

**Show the five first rows in the data**

In [ ]:
data.head()

**Show how many missing values in the columns**

In [ ]:
data.isnull().sum()

**Drop all the none value in the rows**

In [ ]:
data.dropna(inplace=True)

**Get some information a bout the data**

In [ ]:
data.info()

**Get some Statstics information**

In [ ]:
data.describe()

**Here we can extract new features from bedrooms column the first numbers of the beds and the second the numbers of the rooms and others featrues**

In [ ]:
# Extract number of beds and number of bedrooms
data[['num_beds', 'num_bedrooms']] = data['bedrooms'].str.extract('(\d+) beds.*?(\d+) bedrooms').fillna(1)

# print(counts)

**Show the the most freqency numbers of beds and bedrooms the most number is 3 for beds and 2 for the bedrooms**

In [ ]:
data[['num_beds', 'num_bedrooms']].value_counts()

**Fix the price values and delete the Doller sign and convert it to float type**

In [ ]:
data['price']

In [ ]:
data['price'] = data['price'].replace('[\$,]', '', regex=True).astype(float)

**This column has to value the first number represent the rating of place and the second represent the numbers of commints**

In [ ]:
data['rating']

In [ ]:
# Assuming your DataFrame is named 'df' and the column is 'rating_and_comments'
data['rate'] = data['rating'].str.extract(r'(\d+\.\d+)').astype(float)
data['num_comments'] = data['rating'].str.extract(r'\((\d+)\)').astype(float)


# Display the resulting DataFrame
print(data[['rate', 'num_comments']])

In [ ]:
data['price'].describe()

**Drop two columns after makeing extracting new features**

In [ ]:
data1 = data.drop(columns=['rating' , 'bedrooms' , 'date_range' , 'url'])

In [ ]:
data['header'].value_counts()

In [ ]:
import pandas as pd
import re
# City names


# City names mapping
mapping = { 'Apartment in Riyadh': "Riyadh", 'Apartment in Jeddah': "Jeddah", 'Condo in Riyadh': "Riyadh",
           'Apartment in Makkah': "Makkah", 'Condo in Jeddah': "Jeddah", 'Home in Riyadh': "Riyadh",
           'Apartment in King Abdullah Economic City': "King Abdullah", 'Apartment in الرياض': "Riyadh",
           'Hotel in Makkah': "Makkah", 'Apartment in  Muhammadiyah, Jeddah': "Jeddah",
           'Apartment in Mecca': "Makkah", 'Chalet in Riyadh': "Riyadh", 'Condo in Makkah': "Makkah",
           'Room in Riyadh': "Riyadh", 'Home in Jeddah': "Jeddah", 'Villa in Riyadh': "Riyadh",
           'Hut in Jeddah': "Jeddah", 'Cabin in Jeddah': "Jeddah", 'Hut in Taif': "others",
           'Apartment in Diriyah': "others", 'Guest suite in Riyadh': "Riyadh", 'Loft in Jeddah': "Jeddah",
           'Condo in Al Khobar': "others", 'Chalet in Duba': "others", 'Chalet in Mecca': "Makkah",
           'Vacation home in Riyadh': "Riyadh", 'Tiny home in Ragal Almaa': "others", 'Loft in Riyadh City': "Riyadh",
           'Place to stay in Riyadh': "Riyadh", 'Farm stay in Jalajil': "others", 'Barn in Riyadh': "Riyadh",
           'Ranch in AlUla': "others", 'Cabin in At Taif': "others", 'Villa in Jeddah': "Jeddah",
           'Guesthouse in Makkah': "Makkah"}

# Apply mapping to the 'city' column
data['city'] = data['header'].map(mapping)

In [ ]:
data['city'].value_counts()

In [ ]:
data

In [ ]:
df2 = data[['price' , 'num_beds' , 'num_bedrooms' , 'rate' , 'num_comments' , 'city']]

In [ ]:
df2.to_csv("clean_data.csv")

In [ ]:
df2

In [ ]:
df2.info()

In [ ]:
df2.describe()

In [ ]:
df2['price'].value_counts()

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

def remove_outliers(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return data[(data[column] >= lower_bound) & (data[column] <= upper_bound)]

def plot_box_plot(data, column):
    """
    Create a box plot for a specified column in a DataFrame.

    Parameters:
    - data: DataFrame
    - column: str, the column for which the box plot should be created
    """
    plt.figure(figsize=(6, 3))
    sns.boxplot(x=data[column])
    plt.xlabel(column)
    plt.title(f'Box Plot of {column}')
    plt.show()

In [ ]:
column_of_interest = 'num_comments'

# Remove outliers
df3 = remove_outliers(df2 , column_of_interest)

# Create and display the box plot
plot_box_plot(df3 , column_of_interest)

In [ ]:
column_of_interest = 'price'

# Remove outliers
df4 = remove_outliers(df3 , column_of_interest)

# Create and display the box plot
plot_box_plot(df4 , column_of_interest)

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(7,3))
chains=df4['city'].value_counts()
sns.barplot(x=chains,y=chains.index,palette='deep')
plt.title("Most famous city in Sudia Arabia")
plt.xlabel("Number of freqency")

## [Rating distribution]()<a id="6"></a> <br>

In [ ]:
plt.figure(figsize=(4,3))
rating=df4['rate']
sns.distplot(rating,bins=20)

1. Almost more than 60 percent of place has rating between 4.5 and 5.
2. Place having rating less than 4 are very rare.

In [ ]:
plt.figure(figsize=(5,4))
sns.scatterplot(x="rate",y='price' , data = df4) #,hue='online_order',data=cost_dist)
plt.show()

In [ ]:
df4['num_comments'].describe()

In [ ]:
plt.figure(figsize=(5,4))
sns.scatterplot(x="num_comments",y='price' , data = df4 ) #,hue='online_order',data=cost_dist)
plt.show()

In [ ]:
# Specify the columns you want to plot
x_column = 'city'
y_column = 'price'
# Create a scatter plot
plt.figure(figsize=(6, 4))
sns.scatterplot(x=df4[x_column], y=df4[y_column], alpha=0.5)
# Add labels and title
plt.xlabel('City')
plt.ylabel('Price')
plt.title('Scatter Plot of Price by City')

# Show the plot
plt.show()

**we looking teh plot we sea the Riyadh has the heghest price**

### [Distribution of House priceing]()

In [ ]:
plt.figure(figsize=(6,6))
sns.distplot(df4['price'])
plt.show()

In [ ]:
df4_encoded = pd.get_dummies(df4, columns=['city'], prefix='city')

df4_encoded

In [ ]:
# df4 = pd.concat([ clean_data ,dummiess_city ],axis='columns')
# df4.head()

In [ ]:
# Replace spaces with NaN
df4_encoded.replace(' ', pd.NA, inplace=True)
# Drop rows with any null values
df5  = df4_encoded.dropna()
# Display the cleaned DataFrame
print("DataFrame after removing rows with null values or spaces:")
print(df5)

In [ ]:
df5

In [ ]:
import pandas as pd

# Assuming 'df12_cleaned' is your cleaned DataFrame
# This should be the DataFrame after removing rows with null values or spaces

# # Convert True/False to 1/0
# boolean_columns = ['Jeddah', 'King Abdullah', 'Makkah', 'Riyadh', 'others']
# df5[boolean_columns] = df5[boolean_columns].astype(int)

# # Delete the 'city' column
# df5.drop('city', axis=1, inplace=True)

# # Display the modified DataFrame
# print("DataFrame after converting True/False to 1/0 and deleting 'city' column:")
# print(df12_cleaned)

In [ ]:
# # Check for null values
# null_values = df12.isnull().sum()

# # Display the columns with null values
# columns_with_null = null_values[null_values > 0]
# print("Columns with Null Values:")
# print(columns_with_null)

In [ ]:
df5[['city_Jeddah', 'city_King Abdullah', 'city_Makkah', 'city_Riyadh', 'city_others']] = df5[['city_Jeddah', 'city_King Abdullah', 'city_Makkah', 'city_Riyadh', 'city_others']].astype(int)
df5

In [ ]:
df5['num_beds'] = df5['num_beds'].astype(int)
df5['num_bedrooms'] = df5['num_bedrooms'].astype(int)
df5.dtypes

In [ ]:
sns.heatmap(df5.corr())

In [ ]:
# df5['bedrooms'] = df5['num_beds'] + df5['num_bedrooms']

In [ ]:
X = df5.drop(['price'] , axis='columns')
X.head(3)

In [ ]:
y = df5.price
y.head(3)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2 ,random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression
lr_clf = LinearRegression()
lr_clf.fit(X_train,y_train)
lr_clf.score(X_test ,y_test)

In [ ]:
lr_clf.score(X_test ,y_test)

In [ ]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)

cross_val_score(LinearRegression(), X, y, cv=cv)

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Lasso
from sklearn.tree import DecisionTreeRegressor

def find_best_model_using_gridsearchcv(X,y):
    algos = {
        'linear_regression' : {
            'model': LinearRegression(),
            'params': {
                
            }
        },
        'lasso': {
            'model': Lasso(),
            'params': {
                'alpha': [1,2],
                'selection': ['random', 'cyclic']
            }
        },
        'decision_tree': {
            'model': DecisionTreeRegressor(),
            'params': {
                'criterion' : ['mse','friedman_mse'],
                'splitter': ['best','random']
            }
        }
    }
    scores = []
    cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
    for algo_name, config in algos.items():
        gs =  GridSearchCV(config['model'], config['params'], cv=cv, return_train_score=False)
        gs.fit(X,y)
        scores.append({
            'model': algo_name,
            'best_score': gs.best_score_,
            'best_params': gs.best_params_
        })

    return pd.DataFrame(scores,columns=['model','best_score','best_params'])

find_best_model_using_gridsearchcv(X,y)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

# Linear Regression
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)
lr_predictions = lr_model.predict(X_test)

# Logistic Regression (for demonstration purposes; not suitable for regression)
# Note: Logistic Regression is typically used for classification problems
# For regression, consider other algorithms like Linear Regression
logistic_model = LogisticRegression()
logistic_model.fit(X_train, y_train)
logistic_predictions = logistic_model.predict(X_test)

# K-Nearest Neighbors
knn_model = KNeighborsRegressor()
knn_model.fit(X_train, y_train)
knn_predictions = knn_model.predict(X_test)

# Decision Tree
dt_model = DecisionTreeRegressor()
dt_model.fit(X_train, y_train)
dt_predictions = dt_model.predict(X_test)

# Random Forest
rf_model = RandomForestRegressor()
rf_model.fit(X_train, y_train)
rf_predictions = rf_model.predict(X_test)

# Extreme Gradient Boosting (XGBoost)
xgb_model = XGBRegressor()
xgb_model.fit(X_train, y_train)
xgb_predictions = xgb_model.predict(X_test)

# Evaluate performance
def evaluate_model(model, predictions, y_true):
    mse = mean_squared_error(y_true, predictions)
    r2 = r2_score(y_true, predictions)
    print(f"Mean Squared Error: {mse}")
    print(f"R^2 Score: {r2}")

# Evaluate Linear Regression
print("Linear Regression:")
evaluate_model(lr_model, lr_predictions, y_test)

# Evaluate K-Nearest Neighbors
print("\nK-Nearest Neighbors:")
evaluate_model(knn_model, knn_predictions, y_test)

# Evaluate Decision Tree
print("\nDecision Tree:")
evaluate_model(dt_model, dt_predictions, y_test)

# Evaluate Random Forest
print("\nRandom Forest:")
evaluate_model(rf_model, rf_predictions, y_test)

# Evaluate XGBoost
print("\nXGBoost:")
evaluate_model(xgb_model, xgb_predictions, y_test)

# Optionally, plot predictions against true values
plt.scatter(y_test, lr_predictions, label='Linear Regression Predictions')
plt.xlabel('True Values')
plt.ylabel('Predictions')
plt.legend()
plt.show()

In [ ]:
# Create and train the Decision Tree Regressor
dt_model = DecisionTreeRegressor(random_state=42)
dt_model.fit(X_train, y_train)

# Make predictions on the test set
dt_predictions = dt_model.predict(X_test)

# Evaluate model performance
mse = mean_squared_error(y_test, dt_predictions)
r2 = r2_score(y_test, dt_predictions)

print(f"Mean Squared Error: {mse}")
print(f"R^2 Score: {r2}")